name: RAMSBuilder
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.10
targets:
  RAMSBuilder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ramsbuilder
        PRODUCT_NAME: RAMSBuilder
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: RAMSBuilder
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        SUPPORTS_MACCATALYST: NO
    scheme:
      testTargets:
        - RAMSBuilderTests
  RAMSBuilderTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Tests
    dependencies:
      - target: RAMSBuilder
